apiVersion: batch/v1
kind: Job
metadata:
  name: add-vcluster-to-argocd
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: argocd-cli
        image: ubuntu
        command: ["/bin/sh", "-c"]
        args:
        - |
          apt-get update
          apt-get install -y curl
          curl -L https://github.com/argoproj/argo-cd/releases/download/v2.12.4/argocd-linux-amd64 -o /usr/bin/argocd
          chmod +x /usr/bin/argocd
          cp /vcluster/config/config /home/ubuntu/kubeconfig.yaml
          sed -i -e 's/localhost:8443/{{ .Release.Name }}.{{ .Release.Namespace }}/g' /home/ubuntu/kubeconfig.yaml
          argocd cluster add kubernetes-admin@kubernetes \
            --name {{ .Release.Name }} \
            --kubeconfig /home/ubuntu/kubeconfig.yaml \
            --auth-token $ARGOCD_AUTH_TOKEN \
            --server $ARGOCD_SERVER_URL \
            --client-crt /vcluster/config/client-certificate \
            --client-crt-key /vcluster/config/client-key \
            --yes \
            --insecure \
            --upsert \
            --label cluster=preview \
            --annotation branch_slug={{ branch_slug }} \
            --annotation head_short_sha_7={{ head_short_sha_7 }}
        env:
        - name: ARGOCD_AUTH_TOKEN
          value: {{ .Values.argocd.authToken }}
        - name: ARGOCD_SERVER_URL
          value: {{ .Values.argocd.serverUrl }}
        volumeMounts:
          - mountPath: "/vcluster/config"
            name: vcluster-config
            readOnly: true
      restartPolicy: OnFailure
      volumes:
      - name: vcluster-config
        secret:
          secretName: vc-{{ .Release.Name }}
