apiVersion: v1
kind: Pod
metadata:
  name: add-vcluster-to-argocd-pod
spec:
  containers:
  - name: argocd-cli
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - |
      apt-get update
      apt-get install -y curl
      curl -L https://github.com/argoproj/argo-cd/releases/download/v2.12.4/argocd-linux-amd64 -o /usr/bin/argocd
      chmod +x /usr/bin/argocd
    - |
      while true; do
        sleep 300
        echo "Alive"
      done
    # env:
    # - name: ARGOCD_AUTH_TOKEN
    #   valueFrom:
    #     secretKeyRef:
    #       name: vclusteradder
    #       key: password
    volumeMounts:
      - mountPath: "/vcluster/config"
        name: vcluster-config
        readOnly: true
  volumes:
  - name: vcluster-config
    secret:
      secretName: vc-{{ .Release.Name }}