apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- name: argocd-cm
  behavior: merge
  literals:
    - accounts.vclusteradder=apiKey

kind: Kustomization
namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patches:
- path: vclusteradder-overlay.yaml
  target:
    kind: ConfigMap
    name: argocd-rbac-cm
