apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-app-deployment
  namespace: argocd
spec:
  goTemplate: true  
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          cluster-type: 'preview'
  template:
    metadata:
      name: 'myapp-{{.nameNormalized}}'
    spec:
      source:
        repoURL: 'https://github.com/kostis-codefresh/preview-env-manifests.git'
        targetRevision: HEAD
        path: kustomize-preview-app/
        kustomize:
          images:
            - 'docker.io/kostiscodefresh/my-preview-app:{{index .metadata.annotations "head_short_sha_7"}}'        
          patches:
            - target:
                kind: Deployment
                name: simple-deployment
              patch: |-
                - op: replace
                  path: /spec/template/spec/containers/0/env/0
                  value: 
                    name: GIT_BRANCH
                    value: '{{index .metadata.annotations "branch_slug"}}' 
                - op: replace
                  path: /spec/template/spec/containers/0/env/1
                  value: 
                    name: GIT_HASH
                    value: '{{index .metadata.annotations "head_short_sha_7"}}' 
      project: "default"
      destination:
        server: '{{.server}}'
        namespace: 'preview'
      syncPolicy:
        automated:
          prune: true  
        syncOptions:
        - CreateNamespace=true 