---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vcluster-adder
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vcluster-secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
  resourceNames: ["vcluster"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vcluster-secret-reader-binding
subjects:
- kind: ServiceAccount
  name: vcluster-adder
  namespace: default
roleRef:
  kind: ClusterRole
  name: vcluster-secret-reader
  apiGroup: rbac.authorization.k8s.io
